# docker/Dockerfile.web
FROM python:3.10-slim

# Указываем рабочую директорию внутри контейнера
WORKDIR /app

# Создаём пользователя и группу с UID/GID != 0 (чтобы не работать от root)
RUN groupadd -g 1001 myuser && \
    useradd -r -u 1001 -g myuser myuser

# Копируем список зависимостей
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения в контейнер
COPY . /app

# Меняем пользователя в контейнере
USER myuser

# Запускаем Uvicorn-сервер на 8000 порту
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
