# prometheus/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['web:8000']  # Имя сервиса web в docker-compose, порт 8000
        labels:
          env: 'dev'
